### ISSUE TITLE
LKRG fails to load on Debian 10

### ISSUE THREAD

**Issue by gnd** [openwall/lkrg#100]
Hi, 

we are using LKRG on a Debian 10 machine since a year without any problems. However after a recent reboot, we have acquired a new kernel and thus recompiled LKRG from the latest github. This latest version will not load because:

```
[Tue Jul 20 13:17:28 2021] p_lkrg: loading out-of-tree module taints kernel.
[Tue Jul 20 13:17:28 2021] p_lkrg: module verification failed: signature and/or required key missing - tainting kernel
[Tue Jul 20 13:17:28 2021] p_lkrg: Unknown symbol __module_address (err -2)
[Tue Jul 20 13:17:28 2021] p_lkrg: Unknown symbol __module_text_address (err -2)
[Tue Jul 20 13:18:40 2021] p_lkrg: Unknown symbol __module_address (err -2)
[Tue Jul 20 13:18:40 2021] p_lkrg: Unknown symbol __module_text_address (err -2)
[Tue Jul 20 13:21:28 2021] p_lkrg: Unknown symbol __module_address (err -2)
[Tue Jul 20 13:21:28 2021] p_lkrg: Unknown symbol __module_text_address (err -2)
```

Do you have any ideas how to proceed using LKRG ? Thanks a lot. 

```
uname -a
Linux 4.19.0-17-cloud-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64 GNU/Linux
```

**Comment by solardiz** [comment]
Hi @gnd. Thanks for reporting. This looks similar to #93. Perhaps upstream back-ported this change even further, to 4.19 kernels. We'll look into that.

**Comment by oshogbo** [comment]
Just out of curiosity can you run:
```
$ cat /proc/kallsyms | grep __module_address
```

**Comment by solardiz** [comment]
I think the tasks here are to review upstream 4.19.* ChangeLogs (maybe also for even older branches) or stable list postings to confirm the guess and determine the exact kernel revisions where the changes were made. Then adjust LKRG accordingly. Alternatively, we could enable our hack on all kernels (or maybe starting with the oldest currently maintained upstream branch) so that this issue won't bite us again.

@oshogbo Do you possibly have time for this now? ;-)

**Comment by gnd** [comment]
```

**Comment by oshogbo** [comment]
@solardiz I can look into that. Unfortunately I don't have such kernel so it will take me a moment.

**Comment by solardiz** [comment]
@oshogbo I didn't mean you'd actually check the specific Debian kernel - just check the upstream stable changes, like I did to resolve #93.

**Comment by solardiz** [comment]
@gnd We've just merged @oshogbo's changes that should fix this issue. Please test, and if confirmed close this issue, or let us know if anything is still wrong. Thank you!

**Comment by gnd** [comment]
Hi, recompiled the module and it successfully loaded. Thanks a lot !

**Comment by solardiz** [comment]
Thanks for confirming, @gnd!
