### ISSUE TITLE
Signed p_lkrg modules

### ISSUE THREAD

**Issue by itoffshore** [openwall/lkrg#111]
Info more than an issue - for anyone on Arch Linux I build a [signed `p_lkrg`](https://github.com/itoffshore/Arch-SKM/blob/master/arch-sign-modules/arch-sign-modules.install) with [arch-sign-modules](https://aur.archlinux.org/packages/arch-sign-modules/)

```
filename:       /lib/modules/5.12.19-hardened1-1-hardened/kernel/drivers/misc/p_lkrg.ko.xz
license:        GPL v2
description:    pi3's Linux kernel Runtime Guard
author:         Adam 'pi3' Zabrocki (http://pi3.com.pl)
srcversion:     5A0BE68936BF19F7ED8043A
depends:        
retpoline:      Y
name:           p_lkrg
vermagic:       5.12.19-hardened1-1-hardened SMP preempt mod_unload 
sig_id:         PKCS#7
signer:         Local Out of tree kernel module signing key
sig_key:        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
sig_hashalgo:   sha512

```

the only issue I have had is `p_lkrg` with the default options does not seem to like vm's doing `vfio`

**Comment by solardiz** [comment]
> Info more than an issue - for anyone on Arch Linux [...]

Please post about this to the lkrg-users mailing list.

> he only issue I have had is `p_lkrg` with the default options does not seem to like vm's doing `vfio`

Please open a separate issue for this, with more detail in it. Thank you!

**Comment by itoffshore** [comment]
@solardiz - I sent a message to the [mailing list](https://www.openwall.com/lists/lkrg-users/2021/08/20/1)

I will investigate the issue with `vfio` further & open a new issue once I have some relevant information.

**Comment by itoffshore** [comment]
`vfio` works without issue on linux-hardened `5.14.6` with `lkrg` - I didn't really see any slowdown (maybe 1 fps in the Hitman 2 benchmark)
