### ISSUE TITLE
MKOSI container issue

### ISSUE THREAD

**Issue by Adam-pi3** [openwall/lkrg#121]
Hi @vt-alt, can you take a look at the newest issue which breaks mkosi on container environment:

https://github.com/openwall/lkrg/runs/3943837886

Thanks,
Adam

**Comment by vt-alt** [comment]
This is not `mkosi` related Docker based builds (for multiple distros). Perhaps, there is some issue with `alt:sisyphus` docker image. I will investigate further. Thanks.

**Comment by Adam-pi3** [comment]
Thanks @vt-alt for root-causing it :)
