### ISSUE TITLE
mkosi-mainline fails on "grep 'Linux version'"

### ISSUE THREAD

**Issue by solardiz** [openwall/lkrg#126]
mkosi-mainline fails for two days now on `grep 'Linux version'`. I _guess_ the default log level changed such that `boot.log` _does_ have the LKRG message that we grep for, but does not have most of Linux's own boot-up messages. I think we need to either override the log level back (as those messages would be useful for our troubleshooting if/when something else fails later) or remove the `grep 'Linux version'` (not ideal).

**Comment by solardiz** [comment]
Not only mainline, but other mkosi runs are also failing. (It's just that we only had mainline scheduled, so it took until the next PR to notice the rest failing.)

**Comment by vt-alt** [comment]
Yes, it's new feature of Mkosi, I will easily fix it, soon.

**Comment by solardiz** [comment]
Thank you, @vt-alt! How did we start using a new version(?) of mkosi in all of these at once? Since we're testing on various versions of Ubuntu, I'd have expected those versions' packages to be used, no?

**Comment by vt-alt** [comment]
We install with `sudo python3 -m pip install git+https://github.com/systemd/mkosi.git` in these tests. Packaged into Ubuntu `mkosi` had some problems besides being old version.

**Comment by vt-alt** [comment]
I would push the fix yesterday, but I found that `make -j$(nproc)` in `mkosi.build` makes `gcc`s killed (on 20 nproc box). So, I think now should I limit `-j` to something like `2` or not.

**Comment by solardiz** [comment]
@vt-alt The fix has helped - now all green again. Thank you!
