### ISSUE TITLE
Module kobj hash is different alert on Linux 5.10.5

### ISSUE THREAD

**Issue by 0xC0ncord** [openwall/lkrg#38]
After upgrading from kernel 5.10.4 to 5.10.5, I started getting this on boot as soon as systemd starts applying sysctls:

(with log_level=4)
```
Jan 08 20:26:15 bubbles kernel: [p_lkrg] Loading LKRG...
Jan 08 20:26:15 bubbles kernel: EXT4-fs (dm-9): re-mounted. Opts: (null)
Jan 08 20:26:15 bubbles systemd[1]: Finished Remount Root and Kernel File Systems.
Jan 08 20:26:15 bubbles systemd[1]: Condition check resulted in First Boot Wizard being skipped.
Jan 08 20:26:15 bubbles kernel: Freezing user space processes ... (elapsed 0.001 seconds) done.
Jan 08 20:26:15 bubbles kernel: OOM killer disabled.
Jan 08 20:26:15 bubbles kernel: [p_lkrg] [kretprobe] register_kretprobe() for <ovl_create_or_link> failed! [err=-22]
Jan 08 20:26:15 bubbles kernel: [p_lkrg] Trying to find ISRA / CONSTPROP name for <ovl_create_or_link>
Jan 08 20:26:15 bubbles kernel: [p_lkrg] [kretprobe] register_kretprobe() for ovl_create_or_link failed and ISRA / CONSTPROP version not found!
Jan 08 20:26:15 bubbles kernel: [p_lkrg] Can't hook 'ovl_create_or_link' function. This is expected if you are not using OverlayFS.
Jan 08 20:26:15 bubbles kernel: [p_lkrg] [kretprobe] register_kretprobe() for <lookup_fast> failed! [err=-22]
Jan 08 20:26:15 bubbles kernel: [p_lkrg] Trying to find ISRA / CONSTPROP name for <lookup_fast>
Jan 08 20:26:15 bubbles kernel: [p_lkrg] Found CONSTPROP version of function <lookup_fast.constprop.0>
Jan 08 20:26:15 bubbles kernel: [p_lkrg] Trying to find ISRA / CONSTPROP name for <lookup_fast>
Jan 08 20:26:15 bubbles kernel: [p_lkrg] Found CONSTPROP version of function <lookup_fast.constprop.0>
Jan 08 20:26:15 bubbles kernel: [p_lkrg] Trying to find ISRA / CONSTPROP name for <lookup_fast>
Jan 08 20:26:15 bubbles kernel: [p_lkrg] Found CONSTPROP version of function <lookup_fast.constprop.0>
Jan 08 20:26:15 bubbles kernel: [p_lkrg] ISRA / CONSTPROP version was found and hook was planted at <lookup_fast.constprop.0>
Jan 08 20:26:15 bubbles kernel: [p_lkrg] LKRG initialized successfully!
Jan 08 20:26:15 bubbles kernel: OOM killer enabled.
Jan 08 20:26:15 bubbles kernel: Restarting tasks ... done.
Jan 08 20:26:15 bubbles systemd[1]: Condition check resulted in Rebuild Hardware Database being skipped.
Jan 08 20:26:15 bubbles systemd[1]: Condition check resulted in Create System Users being skipped.
Jan 08 20:26:15 bubbles systemd[1]: Starting Create Static Device Nodes in /dev...
Jan 08 20:26:15 bubbles systemd[1]: Finished Load Kernel Modules.
Jan 08 20:26:15 bubbles systemd[1]: Starting Apply Kernel Variables...
Jan 08 20:26:15 bubbles systemd[1]: Finished Create Static Device Nodes in /dev.
Jan 08 20:26:15 bubbles kernel: [p_lkrg] Changing "profile_enforce" logic. From Old[2 | Strict] to new[0 | Log & Accept] one.
Jan 08 20:26:15 bubbles kernel: [p_lkrg] [kINT] New interval => 15
Jan 08 20:26:15 bubbles kernel: [p_lkrg] New log level => 4 (INFO)
Jan 08 20:26:15 bubbles kernel: [p_lkrg] Enabling "blocking modules" feature.
Jan 08 20:26:15 bubbles kernel: [p_lkrg] Hash from CPUs metadata => [0x37ff69e78d7874e9]
Jan 08 20:26:15 bubbles kernel: [p_lkrg] Hash from kernel exception table => [0x61fd07eaab082d44]
Jan 08 20:26:15 bubbles systemd[1]: Reached target Local File Systems (Pre).
Jan 08 20:26:15 bubbles systemd[1]: Attaching device control BPF program to cgroup /system.slice/systemd-udevd.service failed: Invalid argument
Jan 08 20:26:15 bubbles kernel: [p_lkrg] Hash from _stext memory block => [0x8adb21edc9cb3848]
Jan 08 20:26:15 bubbles kernel: [p_lkrg] Hash from _rodata memory block => [0x20308bf5337dbbc8]
Jan 08 20:26:15 bubbles kernel: [p_lkrg] Hash from IOMMU table => [0xffffffff]
Jan 08 20:26:15 bubbles kernel: [p_lkrg] Hash from 'module list' => [0xfe729b8071b68d21]
Jan 08 20:26:15 bubbles kernel: [p_lkrg] Hash from 'module kobj(s)' => [0x956011fdd9b4159f]
Jan 08 20:26:15 bubbles kernel: [p_lkrg] ALERT !!! MODULE KOBJ HASH IS DIFFERENT !!! - it is [0x956011fdd9b4159f] and should be [0x692dcffee8bb996c] !!!
Jan 08 20:26:15 bubbles kernel: [p_lkrg] ALERT !!! SYSTEM HAS BEEN COMPROMISED - DETECTED DIFFERENT 1 CHECKSUMS !!!
```

This did not occur on Linux 5.10.4, and all that has changed was a kernel update and a rebuild of LKRG against the new kernel.

**Comment by 0xC0ncord** [comment]
A quick glance at the history for 5.10.5 leads me to believe that [this commit](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/kernel/module.c?id=38dc717e97153e46375ee21797aa54777e5498f3) is somehow involved.

**Comment by 0xC0ncord** [comment]
> A quick glance at the history for 5.10.5 leads me to believe that [this commit](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/kernel/module.c?id=38dc717e97153e46375ee21797aa54777e5498f3) is somehow involved.

I was able to confirm that this is causing the issue. I was able to workaround it for now by reversing this commit on my local kernel build, but this is certainly an issue that needs to be worked around in LKRG now.

**Comment by solardiz** [comment]
Thank you for reporting this and for your analysis, @0xC0ncord. We're trying to get this fixed upstream: https://lists.openwall.net/linux-kernel/2021/01/10/241

**Comment by solardiz** [comment]
We got a NAK from Greg KH (not a stable API, no support for out-of-tree kernel code, the new code is correct as-is as far as the kernel is concerned), so Adam now intends to work this issue around in LKRG itself. I think that's fine.

**Comment by Adam-pi3** [comment]
Fixed by the following commit:
https://github.com/openwall/lkrg/commit/8814ebe8043d3ff4d7efbb00baacebe6a73bd8f4

**Comment by solardiz** [comment]
FWIW, the kernel change problematic for older LKRG was back-ported to 5.4.87+, so recent LKRG containing Adam's commit referenced above is required for those kernel versions as well.

**Comment by solardiz** [comment]
I've just updated the LKRG homepage to say:

"LKRG 0.8.1 supports Linux kernels up to and including 5.7.x, which were the latest at the time of this LKRG release. For Linux 5.8+ or stable 5.4.87+ (which was released after LKRG 0.8.1 and includes some back-ports from Linux 5.8+), a newer LKRG revision off GitHub is required (and we recommend that you use the latest)."

**Comment by vt-alt** [comment]
We want to add a small integration test (in qemu) in ALT for similar cases. How to manually trigger this issue? Just load any other module after `p_lkrg` is loaded? @wladmis

**Comment by Adam-pi3** [comment]
@vt-alt you don't need to load any other module after LKRG. If you load LKRG and trigger integrity routine ('sysctl lkrg.trigger=1') you should be able to see this issue.

**Comment by vt-alt** [comment]
@Adam-pi3 Thanks much!

**Comment by solardiz** [comment]
@vt-alt Adam's reply was specifically to the question about triggering this issue. To have a higher likelihood of detecting potential future issues like this (not exactly this same issue), I think loading another module after LKRG in the integration test is a good idea.

**Comment by Emm** [comment]
Using `5.14.0-4-amd64 #1 SMP Debian 5.14.16-1 (2021-11-03) x86_64 GNU/Linux` and LKRG 0.9.1-5 from `https://deb.whonix.org`, spurious `MODULE KOBJ HASH IS DIFFERENT` log messages are still an issue

**Comment by solardiz** [comment]
@Emm No, in our understanding it's not "still", but "again" - a different issue that manifests itself the same on 5.14+. We tracked that new issue as #117 and we believe we've fixed it in a9906a6be371d0da669289e76610f40cf9e5d55c. I guess the Whonix package doesn't have that new fix yet, @adrelanos.

**Comment by adrelanos** [comment]
Indeed. Waiting for next stable release of LKRG and also some sort of signed git commits or git tags would be very helpful. (#67)

**Comment by Emm** [comment]
@solardiz , thanks for the prompt answer.
