### ISSUE TITLE
Release LKRG 0.9

### ISSUE THREAD

**Issue by solardiz** [openwall/lkrg#63]
I've just pushed an update to CHANGES that Adam and I have worked on. With this, are we ready to change the version number and make the release, or are there any blockers left? I'd appreciate comments from any/all contributors to this release. Thanks!

**Comment by solardiz** [comment]
OK, the release is blocked at least by #64 now (should be an easy fix).

**Comment by Adam-pi3** [comment]
I've just pushed fixed for #60  and #64. I think we should be fine now...

Btw. Thanks for handling it!

**Comment by solardiz** [comment]
@Adam-pi3 Shouldn't we document #64 and its fix in CHANGES somehow? Any suggested wording?

**Comment by Adam-pi3** [comment]
Hm... I'm fine with reflecting or not reflecting it in CHANGES. I don't know if this needs special handling. However, if you think that we should then what about:

*) Fix SMAP validation for "log and accept" mode

What do you think?

**Comment by solardiz** [comment]
> Fix SMAP validation for "log and accept" mode

I'd like to better understand the impact #64 had. I think in SMAP's "log and accept" mode functionality for SMEP and WP validation was affected, which your suggested description doesn't cover. Also, maybe "log and accept" for SMEP and WP, if both were triggered and in that mode, would also end up silently "accepting" a future SMAP violation, even if SMAP isn't in "log and accept". (I didn't verify these guesses.) So it's tricky.

**Comment by solardiz** [comment]
> I'd like to better understand the impact #64 had.

Looks like the only impact was potentially not logging one or two "Accepting ... new state" messages after the first such message had been logged - so e.g. if a SMAP violation was detected first, then a subsequent SMEP or WP violation wouldn't be logged. This only affected the "log and accept" mode.

Current proposal:

```
 *) Fix logging of WP/SMEP/SMAP violations on systems with SMAP in the "log and 
    accept" mode (previously, one such violation could mute logging of others)
```

**Comment by solardiz** [comment]
After an e-mail discussion with Adam on how exactly LKRG was broken on 32-bit x86, I intend to use this summary:

```
 *) Fix support for 32-bit x86 (was unintentionally broken in LKRG for ages,
    but could mostly work on many pre-5.7 kernel and LKRG builds by "luck")
```

The "luck" here is a bit value in a register, which I guess varies by builds of both the kernel and LKRG. When the luck is "poor", there would probably be false positives or even a boot failure like we see in #49. I wonder if security impact is also possible in some builds.

On 5.7+, LKRG failed reliably for a different reason as seen in #46.

I put the "luck" and "poor" in quotes, because from a different perspective we'd actually have preferred reliable failure, so that we'd have found and fixed the bug long ago.

Thinking out loud:

As I recall, it's the second time that LKRG going directly into register values to access the (sys)call ABI from a kprobe results in a nearly-vulnerability kind of bug. The previous was fixed in b3a499e7f6071e00338f173b2c614227e810397e and prompted the 0.8.1 release. Ideally, we'd avoid messing with the ABI directly, but if we can't then it seems we need a tests coverage that would enable us to detect such issues reliably and promptly. Just how do we reliably detect an issue that might be hidden in 
many builds, though? Even unit tests for individual functions might not be good enough to detect issues like this.

**Comment by solardiz** [comment]
BTW, should we call the release 0.9 or 0.9.0? The previous one was 0.8.1 and we might need more releases before 1.0, so we could as well keep the 3-digit format at least until 1.0. Any preferences?

**Comment by Adam-pi3** [comment]
> BTW, should we call the release 0.9 or 0.9.0? The previous one was 0.8.1 and we might need more releases before 1.0, so we could as well keep the 3-digit format at least until 1.0. Any preferences?

Hm I think it's a good idea to have 3-digit format. We might not use it but maybe we would need it before releasing 1.0. We should try 3 digit format.

**Comment by solardiz** [comment]
We don't have any git tags yet. I think let's start tagging releases like this (and yes, also add this tag for 0.8.1):

```
git tag v0.8.1 4e1dfeb2d16d0f3ea831d9645f16380f6d5d99fe
```

This is the same format of tags that Linux kernel uses, although there they use annotated tags with "Linux ..." in the annotation text.

**Comment by solardiz** [comment]
The top committers since the previous release are:

```
$ git shortlog v0.8.1.. -sn
    65  Adam_pi3
    13  Solar Designer
    12  Mariusz Zaborski
     7  Vladimir D. Seleznev
     5  0xC0ncord
     5  RageLtMan
     5  Vitaly Chikunov
     2  Adam 'pi3' Zabrocki
     2  F0x1fy
     1  William
     1  disrupttheflow
```

I think I'll manually combine the two Adams into one. ;-) We could also add a `.mailmap` and exclude it from tarballs by `.gitattributes`.

**Comment by solardiz** [comment]
> I think I'll manually combine the two Adams into one. ;-)

@Adam-pi3 Which one would you like to keep in the release announcement?

**Comment by Adam-pi3** [comment]
> We don't have any git tags yet. I think let's start tagging releases like this (and yes, also add this tag for 0.8.1):

I've added it and push it. However, I'm not sure if it is reflected in github

> @Adam-pi3 Which one would you like to keep in the release announcement?

In the announcement  I would prefer Adam 'pi3' Zabrocki if possible ;-)

**Comment by solardiz** [comment]
> I've added it and push it. However, I'm not sure if it is reflected in github

I think you didn't push, you'd do that with `git push --tags`. Anyway, I already have the tag set in my local tree and intend to push it from there, so you might want not to push yours (hopefully, it's the same, though).

**Comment by Adam-pi3** [comment]
Ah OK. I will wait for you doing it

**Comment by solardiz** [comment]
> We could also add a `.mailmap` and exclude it from tarballs by `.gitattributes`.

I actually did that thing. I also now have 0.9.0 prepared and tagged locally, not pushed yet in case we need any last-minute change. Release tarballs can now (once I push the tag) be prepared with:

```
git archive --prefix=lkrg-0.9.0/ v0.9.0 > ~/lkrg-0.9.0.tar
```

**Comment by solardiz** [comment]
BTW, I'm happy LKRG became smaller again (despite of some additions):

```
$ git diff --shortstat v0.8.1..v0.9.0 
 126 files changed, 3919 insertions(+), 4375 deletions(-)
```

**Comment by solardiz** [comment]
I've just pushed the release. I'll proceed with further steps (website update, announcements).

**Comment by Adam-pi3** [comment]
Thank you very much!

**Comment by solardiz** [comment]
There are still a few things for me to do on this, but the release is out - closing the issue.
