### ISSUE TITLE
P_PCFI_X86_SMAP is wrong

### ISSUE THREAD

**Issue by solardiz** [openwall/lkrg#64]
`P_PCFI_X86_SMAP` is defined to 3. I think it should be 4, so that it's a separate bit not clashing with others.

Luckily, this bug appears to have little impact: the other two bits are WP and SMEP, and any CPU with SMAP also has SMEP. The only impact appears to be on the "log and accept" mode for SMAP validation, which isn't normally enabled on systems where security matters. In that mode, upon detection of a SMAP violation (SMAP unexpectedly disabled) we'd also clear the WP and SMEP bits in `p_pcfi_CPU_flags`. I didn't look into what exact impact that would have.

Overall, it seems to be that we could drop `p_pcfi_CPU_flags` (after we release 0.9) since we don't appear to rely on it much and since its design is racy anyway (as I had documented in a source code comment). We instead mostly rely on per-flag variables in our RO page (`p_pcfi_CPU_flags` pre-dates those and is arguably now legacy) and indeed on actual CPU flags.

**Comment by Adam-pi3** [comment]
Nice catch! I've just pushed the fix and we can close it
