### ISSUE TITLE
Release LKRG 0.9.1

### ISSUE THREAD

**Issue by solardiz** [openwall/lkrg#73]
This issue is to get opinions on and track tasks required for releasing 0.9.1.

We've already fixed #72. Need to update CHANGES.

Should we also figure out and fix #69 before the release, or will its fix (whatever it is) be part of 0.9.2 or such? I think getting a release out with a fix for #72 is more urgent, so unless we can get #69 fixed really soon we shouldn't delay the release because of it.

**Comment by Adam-pi3** [comment]
I'm not sure how long it might take to address #69. I wonder if we release 0.9.1 now if we can convince `linuxreviews` to update their description about SELinux. We can try to contact them and explain that LKRG strength SELinux by guarding it's configuration and options. However, The bug which they hit was just a mistake during SELinux refactoring work.
What do you think?

**Comment by solardiz** [comment]
I think the timing of our release should be based primarily on what's best for the users and for the project.

As to the review, I further replied to the tweet thread that we think we've fixed the issue in git and asking to re-test and maybe revise the review. There's no reply so far.

**Comment by Adam-pi3** [comment]
Thanks @solardiz. I do agree it will be beneficial if they could retest the recent changes. I'm just wondering that if they don't reply on the twitter maybe email would be better communication channel (just guessing).

**Comment by solardiz** [comment]
> maybe email would be better communication channel

I don't have their e-mail address.

**Comment by solardiz** [comment]
> I don't have their e-mail address.

Or maybe I do - the address they list for "Media inquiries" looks like it's of the right person. Adam, please feel free to send them an e-mail. Please keep me CC'ed if you do.

**Comment by Adam-pi3** [comment]
Per @oyvindsaether comment (https://github.com/openwall/lkrg/issues/72#issuecomment-823611275) issue is fixed. We should good releasing 0.9.1. However, I'm wondering if we should also include `systemd` changes which we are actively discussing and have open PR.

**Comment by solardiz** [comment]
> I'm wondering if we should also include `systemd` changes which we are actively discussing and have open PR.

I think no, we should not. Please don't merge this PR yet. Let's not mix a bug fix and cleanup release with controversial changes (some say the systemd service should be gone, others that it should be revised in different ways) needing additional testing.

Adam, I suggest that meanwhile you try to reproduce #69 in a fork to your own GitHub account with the debugging enabled like you wanted.

**Comment by Adam-pi3** [comment]
From my understanding https://github.com/openwall/lkrg/commit/cccc01dd05805232463729ab305015acb63a87e8 should address #69. I hope we should see it in `mkosi`

**Comment by solardiz** [comment]
> From my understanding [cccc01d](https://github.com/openwall/lkrg/commit/cccc01dd05805232463729ab305015acb63a87e8) should address #69.

Please also suggest a `CHANGES` entry for it - in fact, ideally proposed/draft `CHANGES` entries should be included in commits making the changes themselves (for significant enough changes).

> I hope we should see it in `mkosi`

Not yet - this time it failed differently:

```
Processing triggers for linux-image-unsigned-5.12.0-051200rc8daily20210423-generic (5.12.0-051200rc8daily20210423.202104230206) ...
Errors were encountered while processing:
 linux-headers-5.12.0-051200rc8daily20210423-generic
[...]
‣ Running prepare script...
‣ Error: Workspace command `/root/prepare build` returned non-zero exit code 1.
‣ Unmounting Package Cache...
‣ Unmounting image...
‣ Detaching image file...
Error: Process completed with exit code 1.
```

**Comment by solardiz** [comment]
@Adam-pi3 Did you test cccc01d, and how? This isn't something I can properly review without effectively duplicating your work that brought you to writing that code.

**Comment by solardiz** [comment]
"mkosi boot (mainline)" keeps failing as I described above now - looks unrelated to any changes of ours. @vt-alt Maybe you take a look?

**Comment by Adam-pi3** [comment]
I've compiled locally kernel 5.12-rc8 and I was able to hit that problem not on KVM module (since I don't use KVM but VmWare) but on the core kernel .text session via LTP FTRACE stress test. By having an ability to repro the issue I've test it under the new logic and FP disappeared. I've also tried to cover other cases:
- I've tried to test sync with module subsystem by constantly loading / unloading various modules in the background from a few screen session and in the same time I run LTP project forcing stress tests on FTRACE and tracepoints and didn't see FP. However, all that internal module-loading logic is really over-complicated so maybe I overlooked some corner case.
- I 've tried LTP FTRACE stress tests and running constantly `lkrg.trigger=1` in the background and didn't see FP.

**Comment by Adam-pi3** [comment]
Yes, I saw the problem in `mkosi boot (mainline)`. From my understanding there is a problem with `glibc` version which is used by the environment and `kernel-header` package for the latest kernel which requires newer `glibc`

**Comment by Adam-pi3** [comment]
@solardiz However, I still think I need more time for proper testing of this feature. I expect that I will find some missing sync object on the road...

**Comment by vt-alt** [comment]
It seems they finally switched to `hirsute` from `groovy` for mainline kernels, thus the glibc dependency problem. I will test it.

**Comment by vt-alt** [comment]
> It seems they finally switched to `hirsute` from `groovy` for mainline kernels, thus the glibc dependency problem. I will test it.

FYI. They build on 2021-04-23 first time [on the box `kathleen` which is Ubuntu `hirsute` released on 22 Apr](https://kernel.ubuntu.com/~kernel-ppa/mainline/daily/2021-04-23/summary.yaml) but they use different boxes on different days (`gloin`, `sita`), so I wonder what will happen tomorrow. Maybe just switching to the `hirsute` should work (from now on) since glibc is more backward-compatible than anything.

**Comment by vt-alt** [comment]
Just to cross-reference, I created PR #77.

**Comment by solardiz** [comment]
Thank you, @vt-alt!

**Comment by Adam-pi3** [comment]
@solardiz I was able to produce CSD / on_each_cpu (smp_call_function_single/multi) CPU stuck. However, I'm able to repro this with and without LKRG so it's the problem with the kernel itself not LKRG. However, it's easier to be done with LKRG (probably due the timing). I think we should try releasing the current logic.

**Comment by solardiz** [comment]
> Please also suggest a `CHANGES` entry for it - in fact, ideally proposed/draft `CHANGES` entries should be included in commits making the changes themselves (for significant enough changes).

@Adam-pi3 Does this look good to you? -

```diff
 The following major changes have been made between LKRG 0.9.0 and current:
 
+ *) Support CONFIG_HAVE_STATIC_CALL on Linux 5.10+
  *) Fix SELinux integrity violation false positive bug (introduced into LKRG in
     March 2021 and manifesting itself on Linux 4.17+ when SELinux is already in
     enforcing mode when LKRG is loaded)
+ *) Improve systemd service and its installation, add /etc/sysctl.d/lkrg.conf
  *) Add the debian/ directory in order to support the Debian build system based
     on pbuilder/dpkg-buildpackage
```

(already in a pending commit I have)

**Comment by Adam-pi3** [comment]
Yes, looks perfect - thanks!

Btw. I've verified LKRG under beta-build of Ubuntu 21.04 server and with the kernel 5.12 from ubuntu PPA (https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.12/) and it looks like it works fine.

**Comment by solardiz** [comment]
@morfikov Are updates needed under `debian/` for 0.9.1? I notice `debian/changelog` has an entry for 0.9.0, will you(?) add one for 0.9.1 as well?

**Comment by morfikov** [comment]
I can add, but generally editing of the `debian/` dir should happen after the release, since you have to first provide the source, and then the package can be built. Otherwise the numbers won't match and the package can't be built. But if you want to release the 0.9.1 version soon, I can push a commit. I also made some other changes to the `debian/` dir, so they will be included as well.

**Comment by solardiz** [comment]
> if you want to release the 0.9.1 version soon, I can push a commit.

Yes, please. Will likely release today.

> I also made some other changes to the `debian/` dir, so they will be included as well.

I hope they are very minor. Not a good time to discuss anything controversial when we're about to make a release.

**Comment by morfikov** [comment]
> I hope they are very minor. Not a good time to discuss anything controversial when we're about to make a release.

Nothing to worry about. :)

**Comment by solardiz** [comment]
I've pushed the release and will proceed with further steps now.
