### ISSUE TITLE
Criticism of LKRG systemd service

### ISSUE THREAD

**Issue by solardiz** [openwall/lkrg#74]
https://linuxreviews.org/Linux_Kernel_Runtime_Guard includes this criticism:

> Run sudo make install to install it. It will very impolitely try to enable itself with systemd the moment it is installed by means of a lkrg.service file installed in /etc/systemd/system. If will fail since it doesn't run systemctl daemon-reload to make systemd aware of it and print out an error saying Failed to enable unit: Unit file lkrg.service does not exist. [...]
> 
> [...]
> 
> You may want to eradicate /etc/systemd/system/lkrg.service if you plan on loading it using a file in /etc/modprobe.d/ or other non-systemd means. Preventing the systemd service from loading with systemctl mask lkrg.service won't work since LKRG foolishly puts a file, not a symbolic link, in /etc/systemd/system/.

Is any of this criticism valid? Should we address it, how, and when - probably not in a rushed 0.9.1 release yet (as we might introduce new issues if we do, so need some more testing by users before release)?

**Comment by morfikov** [comment]
To me the LKRG systemd's service doesn't make any sense. You could probably pick up the `modprobe`, `modules` and `sysctl` files from the `debian/` dir and rely on the init to load and configure the module. No extra service is needed here, at least in the case of systemd. If you decide to get rid of the LKRG systemd's service, the config in `debian/` dir has to be updated (in the `debian/rules` file) to use the provided files instead.

**Comment by solardiz** [comment]
We had discussed this on lkrg-users, and IIRC the conclusion was that we needed more control over when exactly the LKRG module is loaded into the kernel and to ensure any sysctl changes would be applied shortly thereafter. Using those separate mechanisms, the timings could be worse and there would be more distro-specific uncertainty. However, we might need to re-read that discussion.

**Comment by solardiz** [comment]
In that context, it is arguably a bug that `debian/` would load LKRG at a different time than `make install` does. Right now, I'd say the bug is in `debian/`.

**Comment by solardiz** [comment]
For the timings, we have this:

```
After=systemd-modules-load.service
Before=systemd-sysctl.service
Before=sysinit.target shutdown.target
```

This currently looks to me quite similar to loading via `modules`, except that we explicitly make LKRG load _after_ all of the other modules listed in there. I am not currently aware of specific reasons for that to be required, but it can probably help avoid triggering some race condition issues between modules going forward.

Possibly more importantly, we also have this:

```
ConditionKernelCommandLine=!nolkrg
```

and this feature is documented in `README`. Does the Debian package produced from `debian/` have it or an equivalent? I guess not. That's a major shortcoming.

**Comment by solardiz** [comment]
Maybe we should add `nolkrg` support to LKRG itself (check it from the kernel module, refuse to initialize LKRG if found) - then this feature would work regardless of init system and also when LKRG is linked into the kernel. What do you think, @Adam-pi3?

**Comment by morfikov** [comment]
>  Does the Debian package produced from debian/ have it or an equivalent? I guess not. That's a major shortcoming.

It depends. The LKRG systemd's service is provided in its separate package. If a user wants this kind of functionality, he can comment out the `p_lkrg` from modules and enable the service manually. In this way the service would take care of loading of the module.

**Comment by solardiz** [comment]
OK, our documentation currently explicitly says that `nolkrg` is specific to the systemd service, so it's not literally a bug that it currently doesn't work without that service:

```
Recovery
--------

To account for the hopefully unlikely, but really unfortunate event that some
incompatibility between the Linux kernel or other components of the system and
LKRG isn't detected prior to LKRG installation, yet leads to system crash on
bootup, we've included support for the "nolkrg" kernel parameter in the systemd
unit file for LKRG.  Thus, if you've followed the above installation procedure
for LKRG with systemd, you may disable LKRG by specifying "nolkrg" on the
kernel command-line via your bootloader.  The system should then boot up
without LKRG, and thus without triggering the problem, letting you fix it.
```

**Comment by oyvindsaether** [comment]
It is hard to give your project any recommendations here.

I will always hate every single package that installs a service file & enables it by default. 

Installing a service file and printing out a message like `type "systemctl enable lkrg.service" to start LKRG at boot` is preferable. There should be a really easy and distribution-correct way to enable it. That's great. It's not that great if you install some web server package and it immediately starts listening on port 80.

There is a "but it's such user-friendly to start automatically" counter-argument that I never understood. Perhaps it is and I don't get it.

I know I would prefer to have both a disabled systemd.service and a commended-out file launching it in /etc/modprobe.d/ and clear instructions on how to enable either of those options.

**Comment by wladmis** [comment]
On Tue, Apr 20, 2021 at 02:43:22PM -0700, Öyvind Sæther wrote:
> It is hard to give your project any recommendations here.
> 
> I will always hate every single package that installs a service file &
> enables it by default. 
> 
> Installing a service file and printing out a message like `type
> "systemctl enable lkrg.service" to start LKRG at boot` is preferable.
> There should be a really easy and distribution-correct way to enable
> it. That's great. It's not that great if you install some web server
> package and it immediately starts listening on port 80.

It is always depends on distro policy how to deal with recently
installed services. For example, Debian policy tells services should be
enabled by default, meanwhile Fedora and ALT policy tells services
should be disabled by default (with a few exceptions like sshd and
crond), and user should enable them explicitly.

For example, ALT package of LKRG does not use Makefile provided by
upstream to install files [1], but still it is an exceptional service
that is enabled by default.

It seems that Pentoo does not use systemd service at all [2], and Whonix
uses its own service [3]. It's always distro choice.

> There is a "but it's such user-friendly to start automatically"
> counter-argument that I never understood. Perhaps it is and I don't
> get it.
> 
> I know I would prefer to have both a disabled systemd.service and a
> commended-out file launching it in /etc/modprobe.d/ and clear
> instructions on how to enable either of those options.

Links:

[1] http://git.altlinux.org/gears/k/kernel-modules-lkrg-std-def.git?p=kernel-modules-lkrg-std-def.git;a=blob;f=kernel-modules-lkrg.spec;h=b7d519521dbc0bc05d042762a36ef763557d7a8d;hb=86bbbd4b0247f6a5ffcfce057e780a0eadcdb1fe#l67
[2] https://github.com/pentoo/pentoo-overlay/blob/e1227f04dd278de4e668114042e980ca0bbe0874/app-antivirus/lkrg/lkrg-0.8.1_p20210341.ebuild
[3] https://github.com/Whonix/lkrg/blob/master/debian/lkrg-dkms.service

**Comment by morfikov** [comment]
> I know I would prefer to have both a disabled systemd.service and a commended-out file launching it in /etc/modprobe.d/ and clear instructions on how to enable either of those options.

That's more of less the current behavior (at least with the .deb packages). The only difference is that when the module is installed via lkrg-dkms.deb, the modules file is also placed with uncommented module name because when a user installs a DKMS module, he would expect the module to be loaded OOTB with the next boot. He can always load the module manually on the current system right after building the module via DKMS. If a user needs the lkrg systemd's service, he can install it separately (or automatically with the`lkrg-dkms` package depending on the system config), and the service is by default disabled as it conflicts with the default configuration, and some user action is needed to make things work.

**Comment by udovdh** [comment]
Related to this, I got:

```
[root@bla lkrg-0.9.0]# make install
make -C /lib/modules/5.11.14/build M=/usr/src/lkrg-0.9.0 modules_install
make[1]: Entering directory '/usr/src/linux-5.11'
  INSTALL /usr/src/lkrg-0.9.0/p_lkrg.ko
  DEPMOD  5.11.15
make[1]: Leaving directory '/usr/src/linux-5.11'
depmod -a
/usr/src/lkrg-0.9.0/scripts/bootup/lkrg-bootup.sh install
 [*] Executing LKRG's bootup installation script
  [+] Systemd detected
      ERROR! lkrg.service file already exists under /etc/systemd/system folder
make: *** [Makefile:103: install] Error 1

So how can I run lkrg for more than one kernel?

**Comment by solardiz** [comment]
@udovdh You're expected to `make uninstall` first.

> So how can I run lkrg for more than one kernel?

If your current kernel is already the new one you want to install LKRG for, then I guess `make uninstall` will leave LKRG for the old kernel in place (it just won't find it). Then your new `make install` will reinstall the systemd service, and it will end up loading LKRG for whatever kernel is actually booted up.

**Comment by solardiz** [comment]
> LKRG foolishly puts a file, not a symbolic link, in /etc/systemd/system/.

What I see on a CentOS 7 system after LKRG's `make install` is this:

```
lrwxrwxrwx. 1 root root 36 Apr 12 19:12 /etc/systemd/system/sysinit.target.wants/lkrg.service -> /usr/lib/systemd/system/lkrg.service
```

So it's a symlink after all (I think created by our invocation of `systemctl enable lkrg.service`), so I don't understand this part of the criticism.

However:

```
-rw-------. 1 solar solar 489 Jun 25  2020 /usr/lib/systemd/system/lkrg.service
```

The installed file pointed-to by the symlink inherits its ownership and permissions from the LKRG build directory. I think this is a bug - we should make the file `root:root` and _maybe_ mode 644 like nearby files are.

I think at the very least we need to replace the `cp -a` in `scripts/bootup/systemd/lkrg-systemd.sh` with some usage of the `install` command.

**Comment by solardiz** [comment]
> I think at the very least we need to replace the `cp -a` in `scripts/bootup/systemd/lkrg-systemd.sh` with some usage of the `install` command.

I just did that. Tested on the mentioned CentOS 7.

**Comment by solardiz** [comment]
> Preventing the systemd service from loading with systemctl mask lkrg.service won't work since LKRG foolishly puts a file, not a symbolic link, in /etc/systemd/system/.

I specifically tested `systemctl mask lkrg.service` and it looks like it works just fine:

```
# systemctl mask lkrg.service
Created symlink from /etc/systemd/system/lkrg.service to /dev/null.
# ls -l /etc/systemd/system/lkrg.service
lrwxrwxrwx. 1 root root 9 Apr 23 11:55 /etc/systemd/system/lkrg.service -> /dev/null
```

**Comment by solardiz** [comment]
> If will fail since it doesn't run systemctl daemon-reload to make systemd aware of it and print out an error saying Failed to enable unit: Unit file lkrg.service does not exist.

I cannot reproduce this issue. Also, searching the systemctl(1) man page for mentions of daemon-reload and reading those pieces my conclusion is that daemon-reload shouldn't be needed and is inappropriate for us to run from there.

@oyvindsaether Can you confirm that out of the issues you listed (quote in my original comment here), only your personal preference not to have the service enabled by default is for real, and the rest are some kind of mistakes of yours? Thanks!

**Comment by solardiz** [comment]
> For the timings, we have this:
> 
> ```
> After=systemd-modules-load.service
> Before=systemd-sysctl.service
> Before=sysinit.target shutdown.target
> ```
> 
> This currently looks to me quite similar to loading via `modules`, except that we explicitly make LKRG load _after_ all of the other modules listed in there. I am not currently aware of specific reasons for that to be required

Here's a reason: on some systems (probably non-desktop), this allows the sysadmin to enable `block_modules` right away. When loading in arbitrary order along with other modules, this obviously wouldn't work reliably (varying subsets of other modules would fail to load). OTOH, enabling `block_modules` from `/etc/sysctl.*` (not as LKRG module parameter) would probably work just as well (assuming that `systemd-sysctl.service` is configured to run only after `systemd-modules-load.service`).

(On desktop systems, this would probably be too early to enable `block_modules`, because starting the X server, etc. may need to load additional graphics hardware drivers.)

**Comment by oyvindsaether** [comment]
> @oyvindsaether Can you confirm that out of the issues you listed (quote in my original comment here), only your personal preference not to have the service enabled by default is for real, and the rest are some kind of mistakes of yours? Thanks!

![ok](https://user-images.githubusercontent.com/68732993/115957365-415c0780-a502-11eb-95e0-11f70a44a6c4.jpg)

I tried the current git right now and it seems to install and enable the service just fine. It didn't before. Replacing cp with install in https://github.com/openwall/lkrg/commit/2d77409585ccdcdddb5b1bb16a604e3b0fcf3ba6 fixed that. I thought it was because it didn't call systemd daemon-reload first but it's not, the 0.9.0 release installs the service file without readable permissions on my box and that was why it failed.

**Comment by solardiz** [comment]
Thank you for testing, @oyvindsaether!

> the 0.9.0 release installs the service file without readable permissions on my box

That's puzzling. I doubt you have a umask of 777, do you? (Instead of `echo $UMASK`, run `umask` to see what the umask is.) Anyway, we should have used `install`, and we do now.

**Comment by oyvindsaether** [comment]
umask says mine is 0027. I probably set it up like that years ago and kind of forgot it's not standard.

**Comment by morfikov** [comment]
> Here's a reason: on some systems (probably non-desktop), this allows the sysadmin to enable `block_modules` right away. When loading in arbitrary order along with other modules, this obviously wouldn't work reliably (varying subsets of other modules would fail to load). OTOH, enabling `block_modules` from `/etc/sysctl.*` (not as LKRG module parameter) would probably work just as well (assuming that `systemd-sysctl.service` is configured to run only after `systemd-modules-load.service`).
> 
> (On desktop systems, this would probably be too early to enable `block_modules`, because starting the X server, etc. may need to load additional graphics hardware drivers.)

Should this really matter? I mean, when you know that some modules will be needed at some point in the future, you shouldn't  enable the module-blocking mechanism at all. On the other hand, when you want to enable it, you should make sure that any module you want to use is loaded at the boot time as soon as possible (in systemd, the `systemd-modules-load.service` is responsible for that). At least I have this kind of a rule and all modules that I need are listed in files under the `/etc/modules-load.d/` dir (but now I use a kernel with all modules builtin).

**Comment by solardiz** [comment]
> I don't like that it automatically enables it on bootup, but.. It does pretty clearly say that it does, and it's not that hard to miss, so it's probably fine.

While it's probably fine, I think we can in fact change this to merely suggesting the user to enable the service. Part of my rationale for that change is:

If a user doesn't read or ignores the advice we give in `README` about testing LKRG prior to installation, then they would be less likely to end up with unbootable system (needing `nolkrg`) as our `make install` could suggest starting the service first, and enabling it to start on bootup next. If starting the service crashes the system, the user wouldn't proceed to enable the service. Technically, we could achieve the same by having `make install` do both of these things, but it starting the service isn't something `make install` is expected to do, so we won't, and this leaves also not enabling the service as the only option.

@Adam-pi3 Do you agree?

**Comment by Adam-pi3** [comment]
@solardiz Yes, in 100%

**Comment by solardiz** [comment]
BTW, our systemd service installation script is the only one where we call a directory a "folder". We should probably fix that.

Also, now that same script installs `/etc/sysctl.d/lkrg.conf`. I think this is OK temporarily, but later this logic should probably be separated from systemd-specific installation.

**Comment by wladmis** [comment]
On Mon, Apr 26, 2021 at 11:37:49AM -0700, Solar Designer wrote:
> BTW, our systemd service installation script is the only one where we
> call a directory a "folder". We should probably fix that.

+

I also would like to rewrite Makefile and install scripts entirely, but
maybe later.

> Also, now that same script installs `/etc/sysctl.d/lkrg.conf`. I think
> this is OK temporarily, but later this logic should probably be
> separated from systemd-specific installation.

**Comment by solardiz** [comment]
There are still many things I dislike about our `scripts/`, but I think we're done with this issue with the commits I've just pushed. I've tested this on a CentOS 7. I'd appreciate others testing on other systems and commenting in here.
