### ISSUE TITLE
Add DKMS configuration file

### ISSUE THREAD

**Issue by solardiz** [openwall/lkrg#75]
This came up in several discussions before - should LKRG perhaps provide its own default DKMS configuration file? Can a reasonable default file exist or is it too distro/system-specific? Should `make install` be installing this file?

We already got DKMS support now under `debian/`, but perhaps we can also have some of it in a non-distro-specific manner?

**Comment by morfikov** [comment]
It depends whether you want to support building the module via DKMS. If so, I think you should provide the `dkms.conf` file.

**Comment by solardiz** [comment]
> It depends whether you want to support building the module via DKMS.

I guess so. It looks like some users want/expect this from us.

> If so, I think you should provide the `dkms.conf` file.

Can you suggest what goes in there? Send us a PR? Thanks!

Another thought I had is: does DKMS run the build as root? That's not ideal if so - while the code being built is to be trusted anyway (it'll be loaded into the kernel), there are additional safety/reliability risks from building anything as root. Perhaps this isn't our job to address this, but is the distro's, or can/should we reasonably do anything about it?

**Comment by solardiz** [comment]
> there are additional safety/reliability risks from building anything as root.

Sometimes security risks, too. A couple of decades ago, then-current now-historical versions of gcc dealt with temporary files unsafely, and could be attacked by another user of the system. Perhaps there are more such toolchain vulnerabilities yet to be introduced/found/fixed.

**Comment by morfikov** [comment]
> Can you suggest what goes in there? Send us a PR? Thanks!

Basically you can use the file I provided in the `debian/` dir, but you have to change the name to `dkms.conf` and edit the `PACKAGE_VERSION` line and keep it updated whenever the version changes. The rest of the file I think can stay the same. There are some additional options that can be set via the file -- take a look at the [manual of the file](https://linux.die.net/man/8/dkms).

> Another thought I had is: does DKMS run the build as root?

Yes. The DKMS binary is under `/usr/sbin/dkms` , at least in Debian.

> That's not ideal if so - while the code being built is to be trusted anyway (it'll be loaded into the kernel), there are additional safety/reliability risks from building anything as root. 

In my case where I use the EFI Secure Boot mechanism, I have to sign any module before it can be loaded into the kernel. I'm not a fan of DKMS modules, that's why I really like the idea of building the module in-tree.

**Comment by solardiz** [comment]
> Basically you can use the file I provided

I'd prefer that you or someone else who actually uses LKRG with DKMS commits this. I don't intend to do it myself.

> edit the PACKAGE_VERSION line and keep it updated whenever the version changes.

I don't mind doing this when preparing LKRG releases.

> The DKMS binary is under /usr/sbin/dkms , at least in Debian.

This doesn't mean it couldn't be run by the distro as non-root. What matters more are permissions on other files it needs to access. The distro would need to allocate a pseudo-user and to give it just sufficient permissions.

**Comment by morfikov** [comment]
I don't really use standalone DKMS, I mean I always build a Debian package using `pbuilder` (`dpkg-buildpackage` in a clean chroot) and when the package is ready, I install it via `apt-get` . All the DKMS work is automated and made during the installation of the .deb package. So I don't even touch the `dkms` command (only the package manager does).
