### ISSUE TITLE
Keep just one sysctl config file

### ISSUE THREAD

**Issue by solardiz** [openwall/lkrg#88]
Due to recent contributions, we have `scripts/bootup/lkrg.conf` and `debian/lkrg-dkms.sysctl`. This is redundant. Since `debian/lkrg-dkms.sysctl` is more complete, perhaps it should be renamed/moved over `scripts/bootup/lkrg.conf` and that file used by the Debian packaging as well.

Further, `debian/lkrg-dkms.sysctl` has a copy of our sysctl descriptions from `README`. When making edits to those, are we going to manually keep them in sync between these two files or should we possibly drop them from one of the two files and refer from it to the other?

**Comment by morfikov** [comment]
You can move the config file inside the lkrg source dir (or some subdir) and maintain only one copy of it. The debian build system can pick up the file from any location in the source.

**Comment by solardiz** [comment]
@morfikov Great. Can you please be the one to send us a PR making this change? I suggest that "`debian/lkrg-dkms.sysctl` [...] be renamed/moved over scripts/bootup/lkrg.conf and that file used by the Debian packaging as well."
