### ISSUE TITLE
"make install" uses flawed heuristics to determine systemd unit directory

### ISSUE THREAD

**Issue by solardiz** [openwall/lkrg#95]
As used in an example in #14 and reported by @adamw-linadm in there for some CentOS 7/8 system, our `scripts/bootup/systemd/lkrg-systemd.sh` fails to determine the actually used systemd unit directory, which it attempts to do with:

```
P_SYSTEMD_DIR="$(systemctl show -p UnitPath | cut -d " " -f5)"
```

Specifically, it always extracts the 5th field, but this can in some setups correspond to a non-existent directory (although on the CentOS 7 where I test it ends up being `/usr/lib/systemd/system`, which does exist).

@Adam-pi3 Why the 5th, and can we do better? Also, what was the reason you didn't hard-code a certain default path here - does it vary between common distros?

Neither I nor I think Adam are familiar with proper systemd service setup. We'd appreciate someone more familiar with this contributing a proper fix/re-work.

**Comment by solardiz** [comment]
> Why the 5th, and can we do better?

One idea is to go over all of these paths with a `for` loop and choose the first that corresponds to an existing directory.

**Comment by 0xC0ncord** [comment]
I think the unit should go into `/etc/systemd/system` unconditionally, as that is the standard location for user-installed system units.

**Comment by wladmis** [comment]
On Fri, May 28, 2021 at 04:15:36PM -0700, 0xC0ncord wrote:
> I think the unit should go into `/etc/systemd/system` unconditionally,
> as that is the standard location for user-installed system units.

+

**Comment by solardiz** [comment]
> I think the unit should go into `/etc/systemd/system` unconditionally, as that is the standard location for user-installed system units.

OK. Want to send us a PR making this change and closing this issue?

> `/lib/systemd/system` and `/usr/lib/systemd/system` also work, but these directories are intended for distributions and package maintainers. If LKRG is installed as a package, the unit should go in one of these instead.

(How) would packagers of LKRG be expected to override this? Is there an established convention on that?

**Comment by solardiz** [comment]
BTW, if/when we change the systemd unit directory path, it will be important for people to use `make uninstall` from the previous LKRG revision before installing the new one. Maybe we'd need to document this somewhere. While it's always a good idea to use `make uninstall` of the same revision that was installed, in practice using `make uninstall` from the new revision's tree worked fine most of the time so far - but will break this time.

**Comment by 0xC0ncord** [comment]
> OK. Want to send us a PR making this change and closing this issue?

Coming right up!

> (How) would packagers of LKRG be expected to override this? Is there an established convention on that?

I'm making an assumption here, but I would't expect packagers to be using the provided script and instead they should be using the tools provided by the packaging mechanism to install the unit. Is it safe to say that the scripts called by `make install` are intended to be used by users and not by package maintainers? If that's the case then it shouldn't be a problem, as the unit should be installed to the proper location anyways.

**Comment by solardiz** [comment]
> Is it safe to say that the scripts called by `make install` are intended to be used by users and not by package maintainers?

I guess no, this isn't a safe assumption, but I'd like to hear from @wladmis on this.

**Comment by wladmis** [comment]
On Sat, May 29, 2021 at 01:30:31PM -0700, Solar Designer wrote:
> > Is it safe to say that the scripts called by `make install` are
> > intended to be used by users and not by package maintainers?
> 
> I guess no, this isn't a safe assumption, but I'd like to hear from
> @wladmis on this.

I do not use `make install` to install files for the ALT package, and I
see that Debian rules file also does not use it. And I thin if some
downstreams do use `make install`, they'll find that smth has changed in
the next release and take care of that.

So I assume it is fair to say that it is a safe assumption.

And usually the package build system provides some kind of guards like
explicit list of files for a package and checker for checker for
filesystem policy.
